### ISSUE TITLE
ovnkube-master crashing with endpoint nil map

### ISSUE THREAD

**Issue by trozet** [ovn-org/ovn-kubernetes#1124]
I0310 13:57:33.978367      48 factory.go:559] added *v1.Service event handler 3
I0310 13:57:33.978403      48 endpoints.go:38] Tcp table: map[https:{[172.17.0.2] 6443}]
Udp table: map[]
I0310 13:57:33.978434      48 loadbalancer.go:97] Creating lb with 2f3f78fd-2ab3-43aa-b3a3-4a4c0da11763, 10.96.0.1, 443, [[172.17.0.2]], 6443
I0310 13:57:33.978497      48 ovs.go:308] using ovn-nbctl daemon mode at [OVN_NB_DAEMON=/var/run/ovn/ovn-nbctl.70.ctl]
I0310 13:57:33.978515      48 ovs.go:211] exec(66): /usr/bin/ovn-nbctl --timeout=15 set load_balancer 2f3f78fd-2ab3-43aa-b3a3-4a4c0da11763 vips:"10.96.0.1:443"="172.17.0.2:6443"
I0310 13:57:33.983289      48 ovs.go:214] exec(66): stdout: ""
I0310 13:57:33.983338      48 ovs.go:215] exec(66): stderr: ""
I0310 13:57:33.983364      48 endpoints.go:243] handling external IPs for svc kubernetes
I0310 13:57:33.983396      48 endpoints.go:49] no service found for endpoint kube-scheduler in namespace kube-system
I0310 13:57:33.983432      48 endpoints.go:49] no service found for endpoint kube-controller-manager in namespace kube-system
I0310 13:57:33.983452      48 endpoints.go:38] Tcp table: map[dns-tcp:{[10.244.0.3 10.244.0.4] 53} metrics:{[10.244.0.3 10.244.0.4] 9153}]
Udp table: map[dns:{[10.244.0.3 10.244.0.4] 53}]
I0310 13:57:33.983485      48 loadbalancer.go:97] Creating lb with 2f3f78fd-2ab3-43aa-b3a3-4a4c0da11763, 10.96.0.10, 53, [[10.244.0.3 10.244.0.4]], 53
I0310 13:57:33.983585      48 ovs.go:308] using ovn-nbctl daemon mode at [OVN_NB_DAEMON=/var/run/ovn/ovn-nbctl.70.ctl]
I0310 13:57:33.983617      48 ovs.go:211] exec(67): /usr/bin/ovn-nbctl --timeout=15 set load_balancer 2f3f78fd-2ab3-43aa-b3a3-4a4c0da11763 vips:"10.96.0.10:53"="10.244.0.3:53,10.244.0.4:53"
I0310 13:57:33.990191      48 ovs.go:214] exec(67): stdout: ""
I0310 13:57:33.990228      48 ovs.go:215] exec(67): stderr: ""
I0310 13:57:33.990245      48 endpoints.go:243] handling external IPs for svc kube-dns
I0310 13:57:33.990263      48 loadbalancer.go:97] Creating lb with 2f3f78fd-2ab3-43aa-b3a3-4a4c0da11763, 10.96.0.10, 9153, [[10.244.0.3 10.244.0.4]], 9153
I0310 13:57:33.990334      48 ovs.go:308] using ovn-nbctl daemon mode at [OVN_NB_DAEMON=/var/run/ovn/ovn-nbctl.70.ctl]
I0310 13:57:33.990355      48 ovs.go:211] exec(68): /usr/bin/ovn-nbctl --timeout=15 set load_balancer 2f3f78fd-2ab3-43aa-b3a3-4a4c0da11763 vips:"10.96.0.10:9153"="10.244.0.3:9153,10.244.0.4:9153"
I0310 13:57:33.994101      48 ovs.go:214] exec(68): stdout: ""
I0310 13:57:33.994127      48 ovs.go:215] exec(68): stderr: ""
I0310 13:57:33.994142      48 endpoints.go:243] handling external IPs for svc kube-dns
I0310 13:57:33.994154      48 loadbalancer.go:97] Creating lb with 911af40d-b682-458c-8759-80bef5444deb, 10.96.0.10, 53, [[10.244.0.3 10.244.0.4]], 53
I0310 13:57:33.994208      48 ovs.go:308] using ovn-nbctl daemon mode at [OVN_NB_DAEMON=/var/run/ovn/ovn-nbctl.70.ctl]
I0310 13:57:33.994228      48 ovs.go:211] exec(69): /usr/bin/ovn-nbctl --timeout=15 set load_balancer 911af40d-b682-458c-8759-80bef5444deb vips:"10.96.0.10:53"="10.244.0.3:53,10.244.0.4:53"
I0310 13:57:33.997528      48 ovs.go:214] exec(69): stdout: ""
I0310 13:57:33.997549      48 ovs.go:215] exec(69): stderr: ""
I0310 13:57:33.997561      48 endpoints.go:243] handling external IPs for svc kube-dns
I0310 13:57:33.997580      48 endpoints.go:54] Skipping service ovnkube-db due to clusterIP = "None"
panic: assignment to entry in nil map

goroutine 172 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).getLbEndpoints(0xc0005b0600, 0xc000138618, 0xc000496c60, 0xc000496c90)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/endpoints.go:34 +0x435
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).AddEndpoints(0xc0005b0600, 0xc000138618, 0x0, 0x0)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/endpoints.go:60 +0x105
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).WatchEndpoints.func1(0x1617b80, 0xc000138618)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ovn.go:401 +0x4d
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:195
k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnAdd(0xc000580b40, 0x18aa540, 0xc000585dc0, 0x1617b80, 0xc000138618)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:227 +0x69
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*Handler).OnAdd(...)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:38
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.newInformer.func1(0xc000496750, 0xc000276800, 0x6, 0x8)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:328 +0x92
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).addHandler(0xc0003be2a0, 0x4, 0xc000580b40, 0x18aa540, 0xc000585dc0, 0xc000276800, 0x6, 0x8, 0xc00002bd28)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:124 +0xaf
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*WatchFactory).addHandler(0xc0003bc200, 0x18f0580, 0x1617b80, 0x0, 0x0, 0x0, 0x18aa540, 0xc000585dc0, 0x0, 0x0, ...)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:558 +0x49e
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*WatchFactory).AddEndpointsHandler(...)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:597
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).WatchEndpoints(0xc0005b0600, 0x0, 0x0)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ovn.go:398 +0x177
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).Run(0xc0005b0600, 0xc000340180, 0x11, 0x0)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ovn.go:165 +0x155
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*HAMasterController).ConfigureAsActive(0xc00028c730, 0x7ffd8c94cba8, 0x11, 0x28, 0xc0000f1fb0)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ha_master.go:205 +0x89
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*HAMasterController).StartHAMasterController.func1(0x18ae5c0, 0xc0004be340)
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ha_master.go:75 +0xd6
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	/home/trozet/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:200 +0xec
info: Waiting for process_ready ovnkube-master to come up, waiting 5s ...

**Comment by trozet** [comment]
I think this is a result of using a protocol other than tcp/udp. Was testing service with sctp:
`

				var portMap map[string]lbEndpoints
				if port.Protocol == kapi.ProtocolUDP {
					portMap = udpPortMap
				} else if port.Protocol == kapi.ProtocolTCP {
					portMap = tcpPortMap
				}
portMap[port.Name] = lbEndpoints{IPs: ips, Port: port.Port}
`

I'll fix this with the sctp service fix for #1120 to error when an unknown protocol is used.
