### ISSUE TITLE
Joining worker nodes fails with IPv4 also

### ISSUE THREAD

**Issue by anildhingra** [ovn-org/ovn-kubernetes#1712]
✗ **Joining worker nodes** 🚜 
ERROR: failed to create cluster: failed to join node with kubeadm: command "docker exec --privileged ovn-worker kubeadm join --config /kind/kubeadm.conf --ignore-preflight-errors=all --v=6" failed with error: exit status 1
Command Output: I0918 09:40:33.917492    1244 join.go:398] [preflight] found NodeName empty; using OS hostname as NodeName
I0918 09:40:33.917539    1244 joinconfiguration.go:74] loading configuration from "/kind/kubeadm.conf"

**[root@ovn contrib]# kind version**
kind v0.8.1 go1.14.2 linux/amd64

**[root@ovn contrib]# docker images**
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
kindest/node        v1.19.0             adeab450f589        2 weeks ago         1.33GB

**Comment by anildhingra** [comment]
with latest version same

**[root@ovn contrib]# kind version**
kind v0.9.0 go1.15.2 linux/amd64

may be due to below

**root@ovn-worker:/# systemctl status kubelet.service**
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Fri 2020-09-18 10:08:46 UTC; 437ms ago
       Docs: http://kubernetes.io/docs/
    Process: 1967 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=255/EXCEPTION)
   Main PID: 1967 (code=exited, status=255/EXCEPTION)

Sep 18 10:08:46 ovn-worker systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Sep 18 10:08:46 ovn-worker systemd[1]: kubelet.service: Failed with result 'exit-code'.



░░ 
░░ The job identifier is 9940.
Sep 18 10:08:26 ovn-worker kubelet[1858]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 18 10:08:26 ovn-worker kubelet[1858]: F0918 10:08:26.181341    1858 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Sep 18 10:08:26 ovn-worker kubelet[1858]: goroutine 1 [running]:
