### ISSUE TITLE
De-flake unit tests

### ISSUE THREAD

**Issue by alexanderConstantinescu** [ovn-org/ovn-kubernetes#2075]
This is an issue tracking the work for de-flaking our unit tests, if you see any build not pass - cuased by a flaking unit test - please post a quick dump of the test failure and link to the build. 

Ex:

**Hybrid SDN Master Operations**

Link: https://github.com/ovn-org/ovn-kubernetes/pull/2002/checks?check_run_id=1981422991

```
Hybrid SDN Master Operations 
  cleans up a Linux node when the OVN hostsubnet annotation is removed
  /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/hybrid-overlay/pkg/controller/master_test.go:303
I0222 10:40:20.722713   22684 config.go:1406] Default config: {MTU:1400 ConntrackZone:64000 EncapType:geneve EncapIP: EncapPort:6081 InactivityProbe:100000 OpenFlowProbe:180 RawClusterSubnets:10.128.0.0/14/23 ClusterSubnets:[{CIDR:10.128.0.0/14 HostSubnetLength:23}]}
I0222 10:40:20.722886   22684 config.go:1407] Logging config: {File: CNIFile:/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log Level:5 LogFileMaxSize:100 LogFileMaxBackups:5 LogFileMaxAge:5 ACLLoggingRateLimit:20}
I0222 10:40:20.723432   22684 config.go:1408] CNI config: {ConfDir:/etc/cni/net.d Plugin:ovn-k8s-cni-overlay}
I0222 10:40:20.723460   22684 config.go:1409] Kubernetes config: {Kubeconfig: CACert: APIServer:http://localhost:8443 Token: CompatServiceCIDR: RawServiceCIDRs:172.16.1.0/24 ServiceCIDRs:[172.16.1.0/24] OVNConfigNamespace:ovn-kubernetes MetricsBindAddress: OVNMetricsBindAddress: MetricsEnablePprof:false OVNEmptyLbEvents:false PodIP: RawNoHostSubnetNodes: NoHostSubnetNodes:nil}
I0222 10:40:20.723523   22684 config.go:1410] Gateway config: {Mode: Interface: NextHop: VLANID:0 NodeportEnable:false DisableSNATMultipleGWs:false V4JoinSubnet:100.64.0.0/16 V6JoinSubnet:fd98::/64}
I0222 10:40:20.723553   22684 config.go:1411] OVN North config: {Address: PrivKey: Cert: CACert: CertCommonName: Scheme:unix northbound:true exec:0xc000519680}
I0222 10:40:20.723580   22684 config.go:1412] OVN South config: {Address: PrivKey: Cert: CACert: CertCommonName: Scheme:unix northbound:false exec:0xc000519680}
I0222 10:40:20.723605   22684 config.go:1413] Hybrid Overlay config: {Enabled:true RawClusterSubnets:11.1.0.0/16/24 ClusterSubnets:[{CIDR:11.1.0.0/16 HostSubnetLength:24}] VXLANPort:4789}
I0222 10:40:20.723824   22684 mock_lsp.go:41] Adding lsp int-node1 to switch node1
I0222 10:40:20.723871   22684 mock_lsp.go:223] Setting dynamic address for LSP int-node1 to 00:00:00:52:19:d2 10.1.2.3
I0222 10:40:20.724159   22684 master.go:99] Starting Hybrid Overlay Master Controller
I0222 10:40:20.724321   22684 reflector.go:219] Starting reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0222 10:40:20.724430   22684 reflector.go:219] Starting reflector *v1.Namespace (0s) from k8s.io/client-go/informers/factory.go:134
I0222 10:40:20.724464   22684 informer.go:178] Starting node informer queue
I0222 10:40:20.724476   22684 reflector.go:255] Listing and watching *v1.Namespace from k8s.io/client-go/informers/factory.go:134
I0222 10:40:20.724477   22684 reflector.go:255] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:134
I0222 10:40:20.724480   22684 informer.go:180] Waiting for node informer caches to sync
I0222 10:40:20.724348   22684 reflector.go:219] Starting reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:134
I0222 10:40:20.724544   22684 reflector.go:255] Listing and watching *v1.Node from k8s.io/client-go/informers/factory.go:134
I0222 10:40:20.824041   22684 shared_informer.go:270] caches populated
I0222 10:40:20.824087   22684 shared_informer.go:270] caches populated
I0222 10:40:20.824102   22684 shared_informer.go:270] caches populated
I0222 10:40:20.824157   22684 kube.go:87] Setting annotations map[k8s.ovn.org/node-subnets:<nil>] on node node1
I0222 10:40:20.824606   22684 shared_informer.go:270] caches populated
I0222 10:40:20.824641   22684 informer.go:186] Starting 10 node queue workers
I0222 10:40:20.824685   22684 informer.go:197] Started node queue workers
I0222 10:40:20.824748   22684 master.go:249] Processing add event for node node1
I0222 10:40:20.824821   22684 master.go:174] No subnet allocation yet for node1
I0222 10:40:20.824842   22684 master.go:242] Removing node node1 hybrid overlay port
I0222 10:40:20.824872   22684 ovs.go:166] exec(8): /fake-bin/ovn-nbctl --timeout=15 -- --if-exists lsp-del int-node1
I0222 10:40:20.824895   22684 ovs.go:169] exec(8): stdout: ""
I0222 10:40:20.824916   22684 ovs.go:170] exec(8): stderr: ""
I0222 10:40:20.824933   22684 kube.go:87] Setting annotations map[k8s.ovn.org/hybrid-overlay-distributed-router-gateway-mac:<nil>] on node node1
I0222 10:40:20.825326   22684 informer.go:294] Successfully synced 'node1'
I0222 10:40:20.825355   22684 master.go:249] Processing add event for node node1
I0222 10:40:20.825393   22684 master.go:174] No subnet allocation yet for node1
I0222 10:40:20.825404   22684 master.go:242] Removing node node1 hybrid overlay port
F0222 10:40:20.825429   22684 exec.go:168] Unexpected command: /fake-bin/ovn-nbctl --timeout=15 -- --if-exists lsp-del int-node1

Executed commands do not match expected commands!
[00]   /fake-bin/ovn-nbctl --timeout=15 -- --if-exists lsp-del int-node1
[01] + /fake-bin/ovn-nbctl --timeout=15 -- --if-exists lsp-del int-node1
goroutine 228 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc00032a2c0, 0x146, 0x2b9)
	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x27fc1a0, 0xc000000003, 0x0, 0x0, 0xc00038e000, 0x269abcd, 0x7, 0xa8, 0x0)
	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/klog/v2.(*loggingT).printf(0x27fc1a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1a52017, 0x1a, 0xc000742a60, 0x2, ...)
	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/klog/v2/klog.go:750 +0x191
```

**Comment by alexanderConstantinescu** [comment]
Another one seen here: https://github.com/alexanderConstantinescu/ovn-kubernetes/runs/2014827349?check_suite_focus=true

**OVN NetworkPolicy Operations during execution** 

```
OVN NetworkPolicy Operations during execution 
  reconciles an updated namespace label
  /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy_test.go:1344
I0302 16:22:02.993970    7091 handler.go:142] Removed *v1.Namespace event handler 6
I0302 16:22:02.994115    7091 handler.go:142] Removed *v1.Namespace event handler 1
I0302 16:22:02.994285    7091 handler.go:142] Removed *v1.Namespace event handler 8
I0302 16:22:02.996764    7091 config.go:1406] Default config: {MTU:1400 ConntrackZone:64000 EncapType:geneve EncapIP: EncapPort:6081 InactivityProbe:100000 OpenFlowProbe:180 RawClusterSubnets:10.128.0.0/14/23 ClusterSubnets:[{CIDR:10.128.0.0/14 HostSubnetLength:23}]}
I0302 16:22:02.996902    7091 config.go:1407] Logging config: {File: CNIFile:/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log Level:5 LogFileMaxSize:100 LogFileMaxBackups:5 LogFileMaxAge:5 ACLLoggingRateLimit:20}
I0302 16:22:02.997000    7091 config.go:1408] CNI config: {ConfDir:/etc/cni/net.d Plugin:ovn-k8s-cni-overlay}
I0302 16:22:02.997036    7091 config.go:1409] Kubernetes config: {Kubeconfig: CACert: APIServer:http://localhost:8443 Token: CompatServiceCIDR: RawServiceCIDRs:172.16.1.0/24 ServiceCIDRs:[172.16.1.0/24] OVNConfigNamespace:ovn-kubernetes MetricsBindAddress: OVNMetricsBindAddress: MetricsEnablePprof:false OVNEmptyLbEvents:false PodIP: RawNoHostSubnetNodes: NoHostSubnetNodes:nil}
I0302 16:22:02.997122    7091 config.go:1410] Gateway config: {Mode: Interface: NextHop: VLANID:0 NodeportEnable:false DisableSNATMultipleGWs:false V4JoinSubnet:100.64.0.0/16 V6JoinSubnet:fd98::/64}
I0302 16:22:02.997188    7091 config.go:1411] OVN North config: {Address: PrivKey: Cert: CACert: CertCommonName: Scheme:unix northbound:true exec:0xc001576780}
I0302 16:22:02.997253    7091 config.go:1412] OVN South config: {Address: PrivKey: Cert: CACert: CertCommonName: Scheme:unix northbound:false exec:0xc001576780}
I0302 16:22:02.997314    7091 config.go:1413] Hybrid Overlay config: {Enabled:false RawClusterSubnets: ClusterSubnets:[] VXLANPort:4789}
I0302 16:22:03.000735    7091 reflector.go:219] Starting reflector *v1beta1.CustomResourceDefinition (0s) from k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go:117
I0302 16:22:03.000808    7091 reflector.go:255] Listing and watching *v1beta1.CustomResourceDefinition from k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go:117
I0302 16:22:03.099982    7091 shared_informer.go:270] caches populated
I0302 16:22:03.101824    7091 reflector.go:219] Starting reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.101952    7091 reflector.go:255] Listing and watching *v1.Service from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.102803    7091 reflector.go:219] Starting reflector *v1.NetworkPolicy (0s) from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.102971    7091 reflector.go:255] Listing and watching *v1.NetworkPolicy from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.105063    7091 reflector.go:219] Starting reflector *v1.Endpoints (0s) from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.105184    7091 reflector.go:255] Listing and watching *v1.Endpoints from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.106262    7091 reflector.go:219] Starting reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.106435    7091 reflector.go:255] Listing and watching *v1.Node from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.107698    7091 reflector.go:219] Starting reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.107808    7091 reflector.go:255] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:134
I0302 16:22:03.109252    7091 reflector.go:219] Starting reflector *v1.Namespace (0s) from k8s.io/client-go/informers/factory.go:134
I0302 16:22:04.323469    7091 handler.go:134] Sending *v1.Pod event handler 9 for removal
I0302 16:22:04.323652    7091 handler.go:134] Sending *v1.Pod event handler 2 for removal
I0302 16:22:04.323789    7091 handler.go:134] Sending *v1.Pod event handler 5 for removal
I0302 16:22:04.323951    7091 handler.go:134] Sending *v1.Service event handler 4 for removal

• Failure [1.332 seconds]
OVN NetworkPolicy Operations
/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy_test.go:585
  during execution
  /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy_test.go:873
    reconciles an updated namespace label [It]
    /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy_test.go:1344

    Timed out after 1.000s.
    Expected
        <bool>: false
    to be true

    /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/address_set/fake_address_set.go:151
------------------------------
OVN NetworkPolicy Operations during execution 
I0302 16:22:04.325428    7091 watch.go:183] Stopping fake watcher.
```

**Comment by alexanderConstantinescu** [comment]
Another, seen here: https://github.com/ovn-org/ovn-kubernetes/runs/2029983928?check_suite_focus=true

**correctly orders serialized informer initial add events and subsequent update events**
```
Watch Factory Operations
/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory_test.go:199
  correctly orders serialized informer initial add events and subsequent update events [It]
  /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory_test.go:855

  Timed out after 10.000s.
  Expected
      <int>: 597
  to equal
      <int>: 598
```

**Comment by tssurya** [comment]
Stale issue. Closing.
