### ISSUE TITLE
Data race with gressPolicy objects

### ISSUE THREAD

**Issue by dcbw** [ovn-org/ovn-kubernetes#2149]
https://pipelines.actions.githubusercontent.com/rx2q6cyVnb1KdY24EzqfkXItIKb3SzT55t8LHdEU6zlqA0chrw/_apis/pipelines/1/runs/32217/signedlogcontent/3?urlExpires=2021-04-01T14%3A29%3A33.9128350Z&urlSigningMethod=HMACV1&urlSignature=14qdPnejwaqQtTgAYzSwApDL1JLwbY0hWn9SVTKNKr0%3D

```
2021-04-01T14:27:09.3350888Z ==================
2021-04-01T14:27:09.3351225Z WARNING: DATA RACE
2021-04-01T14:27:09.3351651Z Write at 0x00c0006684b8 by goroutine 750:
2021-04-01T14:27:09.3352848Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*gressPolicy).destroy()
2021-04-01T14:27:09.3353961Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/gress_policy.go:457 +0xaf
2021-04-01T14:27:09.3355281Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).destroyNetworkPolicy()
2021-04-01T14:27:09.3356407Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy.go:907 +0x304
2021-04-01T14:27:09.3357556Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).deleteNetworkPolicy()
2021-04-01T14:27:09.3358684Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy.go:884 +0x3ef
2021-04-01T14:27:09.3359893Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).WatchNetworkPolicy.func3()
2021-04-01T14:27:09.3361232Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ovn.go:651 +0x5c
2021-04-01T14:27:09.3362617Z   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete()
2021-04-01T14:27:09.3364307Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:245 +0x90
2021-04-01T14:27:09.3365623Z   k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnDelete()
2021-04-01T14:27:09.3366285Z       <autogenerated>:1 +0x2a
2021-04-01T14:27:09.3367486Z   k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnDelete()
2021-04-01T14:27:09.3368884Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:288 +0x7a
2021-04-01T14:27:09.3370206Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*Handler).OnDelete()
2021-04-01T14:27:09.3371395Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:50 +0xa8
2021-04-01T14:27:09.3372818Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).newFederatedHandler.func3.1()
2021-04-01T14:27:09.3374017Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:263 +0x54
2021-04-01T14:27:09.3375080Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).forEachHandler()
2021-04-01T14:27:09.3376167Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:105 +0x221
2021-04-01T14:27:09.3377735Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).newFederatedHandler.func3()
2021-04-01T14:27:09.3379002Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:262 +0x1e6
2021-04-01T14:27:09.3380439Z   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete()
2021-04-01T14:27:09.3382235Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:245 +0x90
2021-04-01T14:27:09.3383460Z   k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnDelete()
2021-04-01T14:27:09.3384145Z       <autogenerated>:1 +0x2a
2021-04-01T14:27:09.3385683Z   k8s.io/client-go/tools/cache.(*processorListener).run.func1()
2021-04-01T14:27:09.3388097Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:779 +0x2b1
2021-04-01T14:27:09.3389576Z   k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
2021-04-01T14:27:09.3391128Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x75
2021-04-01T14:27:09.3391980Z   k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
2021-04-01T14:27:09.3393765Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xba
2021-04-01T14:27:09.3394682Z   k8s.io/apimachinery/pkg/util/wait.JitterUntil()
2021-04-01T14:27:09.3396047Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x114
2021-04-01T14:27:09.3397079Z   k8s.io/apimachinery/pkg/util/wait.Until()
2021-04-01T14:27:09.3398356Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0xa4
2021-04-01T14:27:09.3399529Z   k8s.io/client-go/tools/cache.(*processorListener).run()
2021-04-01T14:27:09.3400672Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:771 +0x4d
2021-04-01T14:27:09.3401694Z   k8s.io/client-go/tools/cache.(*processorListener).run-fm()
2021-04-01T14:27:09.3402839Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:765 +0x4a
2021-04-01T14:27:09.3404054Z   k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
2021-04-01T14:27:09.3405123Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x6d
2021-04-01T14:27:09.3405671Z 
2021-04-01T14:27:09.3406097Z Previous read at 0x00c0006684b8 by goroutine 906:
2021-04-01T14:27:09.3407207Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*gressPolicy).addPeerPod()
2021-04-01T14:27:09.3408323Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/gress_policy.go:128 +0x64
2021-04-01T14:27:09.3409981Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).handlePeerPodSelectorAddUpdate()
2021-04-01T14:27:09.3411206Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy.go:926 +0x90
2021-04-01T14:27:09.3412586Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).handlePeerPodSelector.func3()
2021-04-01T14:27:09.3414272Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy.go:1015 +0x5e
2021-04-01T14:27:09.3415519Z   k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate()
2021-04-01T14:27:09.3417334Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:238 +0xa5
2021-04-01T14:27:09.3419039Z   k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnUpdate()
2021-04-01T14:27:09.3419728Z       <autogenerated>:1 +0x2e
2021-04-01T14:27:09.3421037Z   k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate()
2021-04-01T14:27:09.3422657Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:273 +0x136
2021-04-01T14:27:09.3423805Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*Handler).OnUpdate()
2021-04-01T14:27:09.3424869Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:44 +0xbc
2021-04-01T14:27:09.3426586Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).newFederatedQueuedHandler.func2.1.1()
2021-04-01T14:27:09.3428031Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:221 +0xa8
2021-04-01T14:27:09.3429237Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).forEachQueuedHandler()
2021-04-01T14:27:09.3430802Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:90 +0x2c6
2021-04-01T14:27:09.3432381Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).newFederatedQueuedHandler.func2.1()
2021-04-01T14:27:09.3433927Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:220 +0x69
2021-04-01T14:27:09.3435323Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).processEvents()
2021-04-01T14:27:09.3436494Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:157 +0xb9
2021-04-01T14:27:09.3436993Z 
2021-04-01T14:27:09.3437477Z Goroutine 750 (running) created at:
2021-04-01T14:27:09.3438248Z   k8s.io/apimachinery/pkg/util/wait.(*Group).Start()
2021-04-01T14:27:09.3439350Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x70
2021-04-01T14:27:09.3440380Z   k8s.io/client-go/tools/cache.(*sharedProcessor).run.func1()
2021-04-01T14:27:09.3441563Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:623 +0x1cb
2021-04-01T14:27:09.3442771Z   k8s.io/client-go/tools/cache.(*sharedProcessor).run()
2021-04-01T14:27:09.3443956Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:627 +0x55
2021-04-01T14:27:09.3445015Z   k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm()
2021-04-01T14:27:09.3446550Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/shared_informer.go:618 +0x54
2021-04-01T14:27:09.3447721Z   k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
2021-04-01T14:27:09.3449348Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x45
2021-04-01T14:27:09.3450551Z   k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
2021-04-01T14:27:09.3452033Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x6d
2021-04-01T14:27:09.3452609Z 
2021-04-01T14:27:09.3453196Z Goroutine 906 (running) created at:
2021-04-01T14:27:09.3454453Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.newQueuedInformer()
2021-04-01T14:27:09.3455789Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:348 +0x1c4
2021-04-01T14:27:09.3457419Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.NewMasterWatchFactory()
2021-04-01T14:27:09.3458956Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/factory.go:132 +0x6ca
2021-04-01T14:27:09.3462300Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*FakeOVN).init()
2021-04-01T14:27:09.3463744Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ovn_test.go:97 +0xc7
2021-04-01T14:27:09.3465420Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*FakeOVN).start()
2021-04-01T14:27:09.3467007Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ovn_test.go:76 +0x584
2021-04-01T14:27:09.3468159Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.glob..func13.4.7.1()
2021-04-01T14:27:09.3469577Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy_test.go:1504 +0xf64
2021-04-01T14:27:09.3470280Z   github.com/urfave/cli/v2.(*App).RunContext()
2021-04-01T14:27:09.3471409Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/v2/app.go:315 +0xabe
2021-04-01T14:27:09.3472280Z   github.com/urfave/cli/v2.(*App).Run()
2021-04-01T14:27:09.3473449Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/urfave/cli/v2/app.go:215 +0x286
2021-04-01T14:27:09.3474562Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.glob..func13.4.7()
2021-04-01T14:27:09.3475828Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy_test.go:1541 +0x173
2021-04-01T14:27:09.3476616Z   github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
2021-04-01T14:27:09.3477916Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xfc
2021-04-01T14:27:09.3478782Z   github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
2021-04-01T14:27:09.3479869Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0x184
2021-04-01T14:27:09.3480717Z   github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
2021-04-01T14:27:09.3481911Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/leafnodes/it_node.go:26 +0xb9
2021-04-01T14:27:09.3482778Z   github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
2021-04-01T14:27:09.3483882Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:215 +0x7fd
2021-04-01T14:27:09.3484671Z   github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
2021-04-01T14:27:09.3485693Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x187
2021-04-01T14:27:09.3486588Z   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
2021-04-01T14:27:09.3487947Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x17b
2021-04-01T14:27:09.3488924Z   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
2021-04-01T14:27:09.3490154Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x235
2021-04-01T14:27:09.3491084Z   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()
2021-04-01T14:27:09.3492299Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x145
2021-04-01T14:27:09.3493682Z   github.com/onsi/ginkgo/internal/suite.(*Suite).Run()
2021-04-01T14:27:09.3494993Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:79 +0x839
2021-04-01T14:27:09.3496065Z   github.com/onsi/ginkgo.RunSpecsWithCustomReporters()
2021-04-01T14:27:09.3497967Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:229 +0x357
2021-04-01T14:27:09.3499335Z   github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters()
2021-04-01T14:27:09.3500757Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:217 +0x125
2021-04-01T14:27:09.3501539Z   github.com/onsi/ginkgo.RunSpecs()
2021-04-01T14:27:09.3502703Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:208 +0x1a7
2021-04-01T14:27:09.3504251Z   github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.TestClusterNode()
2021-04-01T14:27:09.3505348Z       /go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/ovn_suite_test.go:12 +0x108
2021-04-01T14:27:09.3505962Z   testing.tRunner()
2021-04-01T14:27:09.3506567Z       /usr/local/go/src/testing/testing.go:1194 +0x202
2021-04-01T14:27:09.3507115Z ==================
2021-04-01T14:27:09.3507642Z panic: runtime error: invalid memory address or nil pointer dereference
2021-04-01T14:27:09.3508351Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x228f375]
2021-04-01T14:27:09.3508701Z 
2021-04-01T14:27:09.3509035Z goroutine 15012 [running]:
2021-04-01T14:27:09.3510092Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*gressPolicy).addPeerPod(0xc000668480, 0xc0012f3c00, 0xc00159cab0, 0x383c401)
2021-04-01T14:27:09.3511254Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/gress_policy.go:138 +0x115
2021-04-01T14:27:09.3512705Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).handlePeerPodSelectorAddUpdate(0xc000314480, 0xc000668480, 0x277cf80, 0xc0012f3c00)
2021-04-01T14:27:09.3514001Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy.go:926 +0x91
2021-04-01T14:27:09.3515376Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn.(*Controller).handlePeerPodSelector.func3(0x277cf80, 0xc0012f2800, 0x277cf80, 0xc0012f3c00)
2021-04-01T14:27:09.3516637Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn/policy.go:1015 +0x5f
2021-04-01T14:27:09.3517790Z k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
2021-04-01T14:27:09.3519100Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:238
2021-04-01T14:27:09.3520817Z k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate(0xc0015b8940, 0x2b44370, 0xc0013fea20, 0x277cf80, 0xc0012f2800, 0x277cf80, 0xc0012f3c00)
2021-04-01T14:27:09.3522869Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/vendor/k8s.io/client-go/tools/cache/controller.go:273 +0x137
2021-04-01T14:27:09.3524649Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*Handler).OnUpdate(0xc0014dd7a0, 0x277cf80, 0xc0012f2800, 0x277cf80, 0xc0012f3c00)
2021-04-01T14:27:09.3526001Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:44 +0xbd
2021-04-01T14:27:09.3527430Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).newFederatedQueuedHandler.func2.1.1(0xc0014dd7a0)
2021-04-01T14:27:09.3528799Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:221 +0xa9
2021-04-01T14:27:09.3530208Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).forEachQueuedHandler(0xc0014d9100, 0xc00071bec0)
2021-04-01T14:27:09.3531573Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:90 +0x2c7
2021-04-01T14:27:09.3533184Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).newFederatedQueuedHandler.func2.1(0xc00159d170)
2021-04-01T14:27:09.3534911Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:220 +0x6a
2021-04-01T14:27:09.3536540Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.(*informer).processEvents(0xc0014d9100, 0xc0013fc000, 0xc000fc1f20)
2021-04-01T14:27:09.3537765Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:157 +0xba
2021-04-01T14:27:09.3539745Z created by github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory.newQueuedInformer
2021-04-01T14:27:09.3540955Z 	/go/src/github.com/ovn-org/ovn-kubernetes/go-controller/pkg/factory/handler.go:348 +0x1c5
2021-04-01T14:27:09.3544090Z FAIL	github.com/ovn-org/ovn-kubernetes/go-controller/pkg/ovn	47.483s
2021-04-01T14:27:09.3587382Z FAIL
2021-04-01T14:27:09.7770010Z ##[error]make: *** [Makefile:42: check] Error 1
2021-04-01T14:27:09.7774801Z ##[error]Process completed with exit code 2.
2021-04-01T14:27:09.7922824Z ##[group]Run actions/upload-artifact@v2
2021-04-01T14:27:09.7923233Z with:
```

**Comment by squeed** [comment]
This should be fixed in #2131

**Comment by tssurya** [comment]
Code here that hits the race is stale. Closing issue.
