### ISSUE TITLE
TC 'Gateway Operations DPU DPU Operations' may segfault rarely

### ISSUE THREAD

**Issue by martinkennelly** [ovn-org/ovn-kubernetes#2846]
Unable to repro locally but seen on test run: https://github.com/ovn-org/ovn-kubernetes/runs/5412510371?check_suite_focus=true
Opening an issue to track this until I understand how its caused:

------------------------------
Gateway Operations DPU DPU Operations 
  sets up a shared interface gateway DPU
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/node/gateway_init_linux_test.go:1060
I0303 19:30:35.341440   19058 config.go:1783] Default config: {MTU:1400 RoutableMTU:0 ConntrackZone:64000 EncapType:geneve EncapIP: EncapPort:6081 InactivityProbe:100000 OpenFlowProbe:180 MonitorAll:true LFlowCacheEnable:true LFlowCacheLimit:0 LFlowCacheLimitKb:0 RawClusterSubnets:10.1.0.0/16 ClusterSubnets:[{CIDR:10.1.0.0/16 HostSubnetLength:24}]}
I0303 19:30:35.342032   19058 config.go:1784] Logging config: {File: CNIFile:/var/log/ovn-kubernetes/ovn-k8s-cni-overlay.log Level:5 LogFileMaxSize:100 LogFileMaxBackups:5 LogFileMaxAge:5 ACLLoggingRateLimit:20}
I0303 19:30:35.342428   19058 config.go:1785] Monitoring config: {RawNetFlowTargets: RawSFlowTargets: RawIPFIXTargets: NetFlowTargets:[] SFlowTargets:[] IPFIXTargets:[]}
I0303 19:30:35.342754   19058 config.go:1786] IPFIX config: {Sampling:0 CacheActiveTimeout:60 CacheMaxFlows:0}
I0303 19:30:35.342805   19058 config.go:1787] CNI config: {ConfDir:/etc/cni/net.d Plugin:ovn-k8s-cni-overlay}
I0303 19:30:35.343393   19058 config.go:1788] Kubernetes config: {Kubeconfig: CACert: CAData:[] APIServer:http://localhost:8443 Token: CompatServiceCIDR: RawServiceCIDRs:172.16.1.0/24 ServiceCIDRs:[172.16.1.0/24] OVNConfigNamespace:ovn-kubernetes MetricsBindAddress: OVNMetricsBindAddress: MetricsEnablePprof:false OVNEmptyLbEvents:false PodIP: RawNoHostSubnetNodes: NoHostSubnetNodes:nil HostNetworkNamespace: PlatformType:}
I0303 19:30:35.343859   19058 config.go:1789] Gateway config: {Mode:shared Interface:brp0 EgressGWInterface: NextHop: VLANID:0 NodeportEnable:true DisableSNATMultipleGWs:false V4JoinSubnet:100.64.0.0/16 V6JoinSubnet:fd98::/64 DisablePacketMTUCheck:false RouterSubnet:}
I0303 19:30:35.343937   19058 config.go:1790] OVN North config: {Address: PrivKey: Cert: CACert: CertCommonName: Scheme:unix ElectionTimer:0 northbound:true exec:0xc000fbea20}
I0303 19:30:35.344606   19058 config.go:1791] OVN South config: {Address: PrivKey: Cert: CACert: CertCommonName: Scheme:unix ElectionTimer:0 northbound:false exec:0xc000fbea20}
I0303 19:30:35.344945   19058 config.go:1792] Hybrid Overlay config: {Enabled:false RawClusterSubnets: ClusterSubnets:[] VXLANPort:4789}
I0303 19:30:35.345003   19058 config.go:1793] Ovnkube Node config: {Mode:dpu MgmtPortNetdev:pf0vf0 DisableOVNIfaceIdVer:false}
I0303 19:30:35.348309   19058 reflector.go:219] Starting reflector *v1.Service (0s) from k8s.io/client-go/informers/factory.go:134
I0303 19:30:35.348451   19058 reflector.go:255] Listing and watching *v1.Service from k8s.io/client-go/informers/factory.go:134
I0303 19:30:35.350090   19058 reflector.go:219] Starting reflector *v1.Pod (0s) from k8s.io/client-go/informers/factory.go:134
I0303 19:30:35.350510   19058 reflector.go:255] Listing and watching *v1.Pod from k8s.io/client-go/informers/factory.go:134
I0303 19:30:35.351182   19058 reflector.go:219] Starting reflector *v1.Node (0s) from k8s.io/client-go/informers/factory.go:134
I0303 19:30:35.351275   19058 reflector.go:255] Listing and watching *v1.Node from k8s.io/client-go/informers/factory.go:134
I0303 19:30:35.351546   19058 reflector.go:219] Starting reflector *v1.Endpoints (0s) from k8s.io/client-go/informers/factory.go:134
I0303 19:30:35.351629   19058 reflector.go:255] Listing and watching *v1.Endpoints from k8s.io/client-go/informers/factory.go:134
I0303 19:30:35.451760   19058 shared_informer.go:270] caches populated
I0303 19:30:35.452145   19058 shared_informer.go:270] caches populated
I0303 19:30:35.452465   19058 shared_informer.go:270] caches populated
I0303 19:30:35.452700   19058 shared_informer.go:270] caches populated
I0303 19:30:35.452916   19058 kube.go:99] Setting annotations map[k8s.ovn.org/node-subnets:{"default":"10.1.1.0/24"}] on node node1
I0303 19:30:35.454557   19058 helper_linux.go:72] Provided gateway interface "brp0", found as index: 2
I0303 19:30:35.455016   19058 helper_linux.go:98] Found default gateway interface brp0 192.168.1.1
I0303 19:30:35.455241   19058 gateway_shared_intf.go:1164] Creating new shared gateway
I0303 19:30:35.455436   19058 ovs.go:204] Exec(126): /fake-bin/ovs-vsctl --timeout=15 port-to-br brp0
I0303 19:30:35.455492   19058 ovs.go:207] Exec(126): stdout: ""
I0303 19:30:35.455608   19058 ovs.go:208] Exec(126): stderr: ""
I0303 19:30:35.455717   19058 ovs.go:210] Exec(126): err: 
I0303 19:30:35.455944   19058 ovs.go:204] Exec(127): /fake-bin/ovs-vsctl --timeout=15 br-exists brp0
I0303 19:30:35.455980   19058 ovs.go:207] Exec(127): stdout: ""
I0303 19:30:35.456086   19058 ovs.go:208] Exec(127): stderr: ""
I0303 19:30:35.456314   19058 ovs.go:204] Exec(128): /fake-bin/ovs-vsctl --timeout=15 list-ports brp0
I0303 19:30:35.456352   19058 ovs.go:207] Exec(128): stdout: "p0"
I0303 19:30:35.456482   19058 ovs.go:208] Exec(128): stderr: ""
I0303 19:30:35.456711   19058 ovs.go:204] Exec(129): /fake-bin/ovs-vsctl --timeout=15 get Port p0 Interfaces
I0303 19:30:35.456750   19058 ovs.go:207] Exec(129): stdout: "p0"
I0303 19:30:35.456873   19058 ovs.go:208] Exec(129): stderr: ""
I0303 19:30:35.457014   19058 ovs.go:204] Exec(130): /fake-bin/ovs-vsctl --timeout=15 get Interface p0 Type
I0303 19:30:35.457133   19058 ovs.go:207] Exec(130): stdout: "system"
I0303 19:30:35.457272   19058 ovs.go:208] Exec(130): stderr: ""
I0303 19:30:35.457457   19058 ovs.go:204] Exec(131): /fake-bin/ovs-vsctl --timeout=15 get interface p0 ofport
I0303 19:30:35.457490   19058 ovs.go:207] Exec(131): stdout: ""
I0303 19:30:35.457511   19058 ovs.go:208] Exec(131): stderr: ""
I0303 19:30:35.457804   19058 ovs.go:204] Exec(132): /fake-bin/ovs-vsctl --timeout=15 --if-exists get interface brp0 mac_in_use
I0303 19:30:35.457839   19058 ovs.go:207] Exec(132): stdout: "11:22:33:44:55:66"
I0303 19:30:35.457876   19058 ovs.go:208] Exec(132): stderr: ""
I0303 19:30:35.457937   19058 ovs.go:204] Exec(133): /fake-bin/ovs-vsctl --timeout=15 --if-exists get Open_vSwitch . external_ids:ovn-bridge-mappings
I0303 19:30:35.458303   19058 ovs.go:207] Exec(133): stdout: ""
I0303 19:30:35.458359   19058 ovs.go:208] Exec(133): stderr: ""
I0303 19:30:35.458515   19058 ovs.go:204] Exec(134): /fake-bin/ovs-vsctl --timeout=15 set Open_vSwitch . external_ids:ovn-bridge-mappings=physnet:brp0
I0303 19:30:35.458556   19058 ovs.go:207] Exec(134): stdout: ""
I0303 19:30:35.458600   19058 ovs.go:208] Exec(134): stderr: ""
I0303 19:30:35.458696   19058 ovs.go:204] Exec(135): /fake-bin/ovs-vsctl --timeout=15 list-ports brp0
I0303 19:30:35.458734   19058 ovs.go:207] Exec(135): stdout: "pf0hpf"
I0303 19:30:35.458780   19058 ovs.go:208] Exec(135): stderr: ""
I0303 19:30:35.458870   19058 ovs.go:204] Exec(136): /fake-bin/ovs-vsctl --timeout=15 get Port pf0hpf Interfaces
I0303 19:30:35.458894   19058 ovs.go:207] Exec(136): stdout: "pf0hpf"
I0303 19:30:35.458939   19058 ovs.go:208] Exec(136): stderr: ""
I0303 19:30:35.459019   19058 ovs.go:204] Exec(137): /fake-bin/ovs-vsctl --timeout=15 get Interface pf0hpf Name
I0303 19:30:35.459061   19058 ovs.go:207] Exec(137): stdout: "pf0hpf"
I0303 19:30:35.459103   19058 ovs.go:208] Exec(137): stderr: ""
I0303 19:30:35.459624   19058 ovs.go:204] Exec(138): /fake-bin/ovs-vsctl --timeout=15 --if-exists get Open_vSwitch . external_ids:system-id
I0303 19:30:35.459670   19058 ovs.go:207] Exec(138): stdout: "cb9ec8fa-b409-4ef3-9f42-d9283c47aac6"
I0303 19:30:35.459730   19058 ovs.go:208] Exec(138): stderr: ""
I0303 19:30:35.459836   19058 ovs.go:204] Exec(139): /fake-bin/ovs-appctl --timeout=15 dpif/show-dp-features brp0
I0303 19:30:35.459867   19058 ovs.go:207] Exec(139): stdout: "Check pkt length action: Yes"
I0303 19:30:35.459916   19058 ovs.go:208] Exec(139): stderr: ""
I0303 19:30:35.460233   19058 gateway_shared_intf.go:1233] Shared Gateway Creation Complete
I0303 19:30:35.460294   19058 gateway_shared_intf.go:1202] Creating Shared Gateway Openflow Manager
I0303 19:30:35.460370   19058 ovs.go:204] Exec(140): /fake-bin/ovs-vsctl --timeout=15 get Interface patch-brp0_node1-to-br-int ofport
I0303 19:30:35.460402   19058 ovs.go:207] Exec(140): stdout: "5"
I0303 19:30:35.460442   19058 ovs.go:208] Exec(140): stderr: ""
I0303 19:30:35.460528   19058 ovs.go:204] Exec(141): /fake-bin/ovs-vsctl --timeout=15 get interface p0 ofport
I0303 19:30:35.460558   19058 ovs.go:207] Exec(141): stdout: "7"
I0303 19:30:35.460597   19058 ovs.go:208] Exec(141): stderr: ""
I0303 19:30:35.460674   19058 ovs.go:204] Exec(142): /fake-bin/ovs-vsctl --timeout=15 list-ports brp0
I0303 19:30:35.460706   19058 ovs.go:207] Exec(142): stdout: "pf0hpf"
I0303 19:30:35.460753   19058 ovs.go:208] Exec(142): stderr: ""
I0303 19:30:35.460836   19058 ovs.go:204] Exec(143): /fake-bin/ovs-vsctl --timeout=15 get Port pf0hpf Interfaces
I0303 19:30:35.460865   19058 ovs.go:207] Exec(143): stdout: "pf0hpf"
I0303 19:30:35.460905   19058 ovs.go:208] Exec(143): stderr: ""
I0303 19:30:35.460980   19058 ovs.go:204] Exec(144): /fake-bin/ovs-vsctl --timeout=15 get Interface pf0hpf Name
I0303 19:30:35.461012   19058 ovs.go:207] Exec(144): stdout: "pf0hpf"
I0303 19:30:35.461053   19058 ovs.go:208] Exec(144): stderr: ""
I0303 19:30:35.461433   19058 ovs.go:204] Exec(145): /fake-bin/ovs-vsctl --timeout=15 get interface pf0hpf ofport
I0303 19:30:35.461490   19058 ovs.go:207] Exec(145): stdout: "9"
I0303 19:30:35.461671   19058 ovs.go:208] Exec(145): stderr: ""
I0303 19:30:35.462624   19058 node_ip_handler_linux.go:216] Skipping non-useable IP address for host: fe80::a05e:5aff:feb4:cdc4
I0303 19:30:35.462689   19058 node_ip_handler_linux.go:224] Node address annotation being set to: map[192.168.1.101:{}] addrChanged: true
I0303 19:30:35.462747   19058 kube.go:99] Setting annotations map[k8s.ovn.org/host-addresses:["192.168.1.101"]] on node node1
I0303 19:30:35.463880   19058 gateway_shared_intf.go:1221] Creating Shared Gateway Node Port Watcher
I0303 19:30:35.463976   19058 ovs.go:204] Exec(146): /fake-bin/ovs-vsctl --timeout=15 --if-exists get interface patch-brp0_node1-to-br-int ofport
I0303 19:30:35.464011   19058 ovs.go:207] Exec(146): stdout: "5"
I0303 19:30:35.464035   19058 ovs.go:208] Exec(146): stderr: ""
I0303 19:30:35.464323   19058 ovs.go:204] Exec(147): /fake-bin/ovs-vsctl --timeout=15 --if-exists get interface p0 ofport
I0303 19:30:35.464364   19058 ovs.go:207] Exec(147): stdout: "7"
I0303 19:30:35.464410   19058 ovs.go:208] Exec(147): stderr: ""
I0303 19:30:35.464592   19058 healthcheck.go:290] Gateway OpenFlow sync requested
I0303 19:30:35.464630   19058 factory.go:372] Added *v1.Service event handler 1
I0303 19:30:35.464712   19058 factory.go:372] Added *v1.Endpoints event handler 2
I0303 19:30:35.464766   19058 kube.go:99] Setting annotations map[k8s.ovn.org/l3-gateway-config:{"default":{"mode":"shared","interface-id":"brp0_node1","mac-address":"aa:bb:cc:dd:ee:ff","ip-addresses":["192.168.1.10/24"],"ip-address":"192.168.1.10/24","next-hops":["192.168.1.1"],"next-hop":"192.168.1.1","node-port-enable":"true","vlan-id":"0"}} k8s.ovn.org/node-chassis-id:cb9ec8fa-b409-4ef3-9f42-d9283c47aac6 k8s.ovn.org/node-subnets:{"default":"10.1.1.0/24"}] on node node1
I0303 19:30:35.466324   19058 node_ip_handler_linux.go:142] Node IP manager is running
I0303 19:30:35.466390   19058 gateway.go:178] Spawning Conntrack Rule Check Thread
I0303 19:30:35.466661   19058 ovs.go:204] Exec(148): /fake-bin/ovs-ofctl -O OpenFlow13 --bundle replace-flows brp0 -
I0303 19:30:35.466738   19058 ovs.go:207] Exec(148): stdout: ""
I0303 19:30:35.466763   19058 ovs.go:208] Exec(148): stderr: ""
I0303 19:30:35.466891   19058 node_ip_handler_linux.go:216] Skipping non-useable IP address for host: 127.0.0.1
I0303 19:30:35.467052   19058 node_ip_handler_linux.go:216] Skipping non-useable IP address for host: ::1
I0303 19:30:35.467116   19058 node_ip_handler_linux.go:216] Skipping non-useable IP address for host: fe80::6245:bdff:fe00:6d49
I0303 19:30:35.467179   19058 node_ip_handler_linux.go:224] Node address annotation being set to: map[10.1.1.52:{} 172.17.0.1:{}] addrChanged: true
I0303 19:30:35.467298   19058 kube.go:99] Setting annotations map[k8s.ovn.org/host-addresses:["10.1.1.52","172.17.0.1"]] on node node1
E0303 19:30:35.467361   19058 node_ip_handler_linux.go:75] Failed during AddrSubscribe callback: Receive called on a closed socket
E0303 19:30:35.469474   19058 node_ip_handler_linux.go:75] Failed during AddrSubscribe callback: Receive called on a closed socket
I0303 19:30:35.469647   19058 node_ip_handler_linux.go:216] Skipping non-useable IP address for host: 127.0.0.1
I0303 19:30:35.470057   19058 node_ip_handler_linux.go:216] Skipping non-useable IP address for host: ::1
I0303 19:30:35.470095   19058 node_ip_handler_linux.go:216] Skipping non-useable IP address for host: fe80::6245:bdff:fe00:6d49
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x2215d1d]

goroutine 1322 [running]:
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*addressManager).doesNodeHostAddressesMatch(0xc000ce1900)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/node/node_ip_handler_linux.go:160 +0xfd
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*addressManager).sync(0xc000ce1900)
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/node/node_ip_handler_linux.go:223 +0x22f
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*addressManager).Run.func2()
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/node/node_ip_handler_linux.go:86 +0x156
github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*addressManager).Run.func3()
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/node/node_ip_handler_linux.go:106 +0x826
created by github.com/ovn-org/ovn-kubernetes/go-controller/pkg/node.(*addressManager).Run
	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/node/node_ip_handler_linux.go:91 +0x3d4
make: *** [Makefile:46: check] Error 2

**Comment by martinkennelly** [comment]
Seen again here: https://github.com/ovn-org/ovn-kubernetes/runs/5724737227?check_suite_focus=true
Waiting for new netlink version to be pulled to close this.

**Comment by martinkennelly** [comment]
Closing - netlink updated and fix consumed.
