### ISSUE TITLE
Flake:  error deleting subnet 10.1.1.0/24 for node "node1": network 10.1.1.0/24 does not belong to any known range

### ISSUE THREAD

**Issue by andreaskaris** [ovn-org/ovn-kubernetes#3087]
~~~
 I0722 17:47:04.449322   21869 cache.go:982] cache "msg"="processing update" "database"="OVN_Northbound" "table"="NAT" "uuid"="d303d6e2-950d-4f07-8217-b023818379a1" 
2022/07/22 17:47:04 cache: "caller"={"file":"cache.go","line":982} "level"=5 "msg"="processing update" "uuid"="d303d6e2-950d-4f07-8217-b023818379a1" "table"="NAT"
2022/07/22 17:47:04 cache: "caller"={"file":"cache.go","line":982} "level"=5 "msg"="processing update" "uuid"="b16f8d3a-6511-4a41-9087-56d9cde8df24" "table"="Logical_Router"
I0722 17:47:04.451369   21869 obj_retry.go:1657] Delete event received for *v1.Node node1
I0722 17:47:04.451712   21869 master.go:1417] Deleting Node "node1". Removing the node from various caches
E0722 17:47:04.451970   21869 obj_retry.go:1671] Failed to delete *v1.Node node1, error: error deleting node node1 HostSubnet 10.1.1.0/24: error deleting subnet 10.1.1.0/24 for node "node1": network 10.1.1.0/24 does not belong to any known range
STEP: retry entry new obj should be nil
STEP: retry entry old obj should not be nil
I0722 17:47:04.462392   21869 obj_retry.go:269] Iterate retry objects requested (resource *v1.Node)
I0722 17:47:04.462582   21869 obj_retry.go:1312] Retry channel got triggered: retrying failed objects of type *v1.Node
coverage: 31.8% of statements
panic: test timed out after 10m0s
goroutine 9263 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:1788 +0xbb
created by time.goFunc
	/opt/hostedtoolcache/go/1.17.6/x64/src/time/sleep.go:180 +0x4a
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc0000a6820, {0x2a75f28, 0xf}, 0x2b7a140)
~~~
https://github.com/ovn-org/ovn-kubernetes/runs/7472977076?check_suite_focus=true

**Comment by npinaeva** [comment]
Closing since it hasn't been updated for a while
