### ISSUE TITLE
UTs timing out: panic: test timed out after 10m0s

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#3615]
```
2023-05-25T18:16:28.5781062Z I0525 18:16:28.577787   21779 client.go:260]  "msg"="successfully connected" "database"="OVN_Northbound" "endpoint"="unix:/tmp/ovsdb-fe1a6f44716819a55078a4c8127cd73d" "sid"="c6a8cb4b"
2023-05-25T18:16:28.5815304Z I0525 18:16:28.581240   21779 cache.go:1028] cache "msg"="processing update" "database"="OVN_Northbound" "table"="Database" "uuid"="f704540e-1fe6-4a98-b2ed-ae835aa988a0"
2023-05-25T18:16:28.5822004Z I0525 18:16:28.581967   21779 cache.go:1036] cache "msg"="creating row" "database"="OVN_Northbound" "model"="&{UUID:f704540e-1fe6-4a98-b2ed-ae835aa988a0 Cid:<nil> Connected:true Index:<nil> Leader:true Model:clustered Name:OVN_Northbound Schema:<nil> Sid:0xc019ced240}" "table"="Database" "uuid"="f704540e-1fe6-4a98-b2ed-ae835aa988a0"
2023-05-25T18:16:28.5936824Z I0525 18:16:28.593414   21779 cache.go:1028] cache "msg"="processing update" "database"="OVN_Northbound" "table"="Logical_Switch" "uuid"="ce86ca71-2bf1-40c5-8029-8acc1be23502"
2023-05-25T18:16:28.5942590Z I0525 18:16:28.594025   21779 cache.go:1036] cache "msg"="creating row" "database"="OVN_Northbound" "model"="&{UUID:ce86ca71-2bf1-40c5-8029-8acc1be23502 ACLs:[] Copp:<nil> DNSRecords:[] ExternalIDs:map[] ForwardingGroups:[] LoadBalancer:[] LoadBalancerGroup:[] Name:node1 OtherConfig:map[] Ports:[] QOSRules:[]}" "table"="Logical_Switch" "uuid"="ce86ca71-2bf1-40c5-8029-8acc1be23502"
2023-05-25T18:16:28.6150807Z coverage: 68.1% of statements
2023-05-25T18:16:28.6184588Z panic: test timed out after 10m0s
2023-05-25T18:16:28.6185295Z 
2023-05-25T18:16:28.6187485Z goroutine 63332 [running]:
2023-05-25T18:16:28.6189516Z testing.(*M).startAlarm.func1()
2023-05-25T18:16:28.6192185Z 	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:2029 +0xbb
2023-05-25T18:16:28.6194148Z created by time.goFunc
2023-05-25T18:16:28.6198025Z 	/opt/hostedtoolcache/go/1.18.4/x64/src/time/sleep.go:176 +0x48
2023-05-25T18:16:28.6198560Z 
2023-05-25T18:16:28.6201216Z goroutine 1 [chan receive, 9 minutes]:
2023-05-25T18:16:28.6203455Z testing.(*T).Run(0xc0000d2340, {0x3213619, 0xf}, 0x33570c8)
2023-05-25T18:16:28.6205475Z 	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1487 +0x750
2023-05-25T18:16:28.6206748Z testing.runTests.func1(0x0?)
2023-05-25T18:16:28.6209502Z 	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1839 +0x9a
2023-05-25T18:16:28.6210992Z testing.tRunner(0xc0000d2340, 0xc00042db68)
2023-05-25T18:16:28.6212987Z 	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1439 +0x214
2023-05-25T18:16:28.6217247Z testing.runTests(0xc000fdafa0?, {0x4a62740, 0x9, 0x9}, {0x40?, 0x2ee26e0?, 0x4a968c0?})
2023-05-25T18:16:28.6219000Z 	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1837 +0x7e5
2023-05-25T18:16:28.6219756Z testing.(*M).Run(0xc000fdafa0)
2023-05-25T18:16:28.6222823Z 	/opt/hostedtoolcache/go/1.18.4/x64/src/testing/testing.go:1719 +0xa72
2023-05-25T18:16:28.6223768Z main.main()
2023-05-25T18:16:28.6227071Z 	_testmain.go:175 +0x3aa
2023-05-25T18:16:28.6227438Z 
```

**Comment by tssurya** [comment]
https://github.com/ovn-org/ovn-kubernetes/actions/runs/5083032709/jobs/9133514198?pr=3605

**Comment by npinaeva** [comment]
Closing since it hasn't been updated for a while
