### ISSUE TITLE
Panics in UTs that don't show up because we don't check for things correctly

### ISSUE THREAD

**Issue by tssurya** [ovn-org/ovn-kubernetes#4656]
### What would you like to see added/updated/deleted in our unit tests?

```
2024-08-14T07:04:37.0376792Z [0mMananagement port DPU tests[0m [90mCreate Management port DPU[0m 
2024-08-14T07:04:37.0377453Z   [1mConfigures VF representor and connects it to OVS bridge[0m
2024-08-14T07:04:37.0378376Z   [37m/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/node/management-port_dpu_test.go:120[0m
2024-08-14T07:04:37.0379509Z I0814 07:04:37.033523   34545 management-port-dpu.go:47] Lookup representor link and existing management port for 'enp3s0f0v0'
2024-08-14T07:04:37.0380527Z I0814 07:04:37.035212   34545 management-port-dpu.go:61] Setup representor management port: enp3s0f0v0
2024-08-14T07:04:37.0381722Z E0814 07:04:37.037074   34545 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
2024-08-14T07:04:37.0382619Z goroutine 33 [running]:
2024-08-14T07:04:37.0383195Z k8s.io/apimachinery/pkg/util/runtime.logPanic({0x32369c0, 0x4ebb960})
2024-08-14T07:04:37.0384219Z 	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0xd3
2024-08-14T07:04:37.0385134Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x3728530?})
2024-08-14T07:04:37.0386280Z 	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0xa8
2024-08-14T07:04:37.0387016Z panic({0x32369c0?, 0x4ebb960?})
2024-08-14T07:04:37.0387484Z 	/opt/hostedtoolcache/go/1.22.0/x64/src/runtime/panic.go:770 +0x132
2024-08-14T07:04:37.0388403Z github.com/ovn-org/ovn-kubernetes/go-controller/pkg/util.UpdateNodeManagementPortMACAddressesWithRetry.func1()
2024-08-14T07:04:37.0389494Z 	/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/util/node_annotations.go:431 +0xae
```

### Why is this needed?

UTs pass fine but this is annoying

**Comment by tssurya** [comment]
Credit to @jcaamano for spotting this
